### ISSUE TITLE
why you add  6, 1 in EstimateTransmission, despite of function definition need 3 args !?

### ISSUE THREAD

**Issue by mzalaki00** [TripleJ2543/Low_Light_Pattern_Recognition#1]
File "/content/Run_LowLight_Image_Enhancement_Pixel_Adaptive.py", line 156, in main
    Transmap = EstimateTransmission(float_image, NormImg, gamma_max, 6, 1)
TypeError: EstimateTransmission() takes from 2 to 3 positional arguments but 5 were given

**Comment by TripleJ2543** [comment]
Thank you for finding the error.

It was my mistake. It was something I missed during the testing process.

You can proceed by removing the ", 6, 1" part.

I have corrected it and uploaded it again.

Thank you.
